[project]
name = "sdag"
version = "0.1.0"
description = "DAGs for Slurm"
readme = "README.md"
authors = [
    { name = "Alessandro Rognoni", email = "alessandro.rognoni@domyn.com" }
]
requires-python = ">=3.10"
dependencies = [
    "pydantic>=2.11.9",
    "pydantic-settings>=2.11.0",
]

[project.scripts]
sdag = "sdag.__main__:main"

[project.entry-points."uv.run"]
sdag = "sdag.__main__:main"

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
# "extension-module" tells pyo3 we want to build an extension module (skips linking against libpython.so)
features = ["pyo3/extension-module"]
python-packages = ["sdag"]
strip = true

[tool.ruff]
line-length = 79
extend-exclude = [".ipynb_checkpoints", "docs"]

[tool.ruff.lint]
select = [
    "F",
    "E",
    "W",
    "C90",
    "I",
    "N",
    "D",
    "UP",
    "YTT",
    "BLE",
    "FBT",
    "B",
    "B9",
    "A",
    "C4",
    "T10",
    "EM",
    "ISC",
    "ICN",
    "LOG",
    "G",
    "PT",
    "RSE",
    "RET",
    "SLF",
    "SIM",
    "ARG",
    "PTH",
    "TRY",
    "NPY",
    "PERF",
    "RUF",
]
ignore = [
    # Missing docstring in public package
    "D100",
    # Missing docstring in public module
    "D104",
    # Not supported by Pydantic
    "UP046",
    # Caching default value is set in the decorator
    "FBT001",
]

[tool.ruff.lint.extend-per-file-ignores]
# ignore unused imports
"__init__.py" = ["F401"]
# ignore pydocstyle rules for tests
# Tests can access private functions
"tests/*" = ["D", "SLF001"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.pyright]
include = ["src", "tests"]
exclude = [
    "**/__pycache__",
]
defineConstant = { DEBUG = true }
reportMissingImports = "error"
reportMissingTypeStubs = false

pythonPlatform = "Linux"
venvPath = "."
venv = ".venv"

[dependency-groups]
test = [
    "pytest>=8.4.2",
    "pytest-mock>=3.15.1",
]
