name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: install rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: cache rust
        uses: Swatinem/rust-cache@v2
      - name: Install UV
        run: pipx install uv
      - name: Define a cache for the virtual environment
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: venv-${{ hashFiles('uv.lock') }}
      - name: Install dependencies
        run: uv sync --group test
      - name: Run Python tests
        run: uv run pytest -v
      - name: Run hooks
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
